version: "2"

services:

  www:
    image: penkit/site:latest
    restart: unless-stopped
    labels:
    - "traefik.backend=penkit"
    - "traefik.frontend.rule=Host:penkit.io"
    - "traefik.port=8080"

  packages:
    image: dhumphreys88/httpd:latest
    restart: unless-stopped
    labels:
    - "traefik.backend=packages"
    - "traefik.frontend.rule=Host:apk.penkit.io"
    - "traefik.port=8080"
    volumes:
    - "/home/core/packages:/opt/www"

  traefik:
    image: traefik:latest
    command: --web --docker
    restart: unless-stopped
    ports:
    - "80:80"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/dev/null:/traefik.toml"
